AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  WebSubVerificationToken:
    Type: String
    NoEcho: true
  WebHookURL:
    Type: String
    NoEcho: true

Resources:
  YouTubeVideoDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['-', ['youtube-video-data', !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      AttributeDefinitions:
        -
          AttributeName: VideoID
          AttributeType: S
      KeySchema:
        -
          AttributeName: VideoID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Path: /
      Policies:
        - PolicyName: dynamodb-access-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:Get*'
                  - 'dynamodb:PutItem'
                Resource: !GetAtt YouTubeVideoDataTable.Arn

  WebSubFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda
      CodeUri: 'cmd/lambda'
      Runtime: go1.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        VerifySubscription:
          Type: HttpApi
          Properties:
            Path: '/websub/subscribe'
            Method: get
            PayloadFormatVersion: '1.0'
        ReceiveNotification:
          Type: HttpApi
          Properties:
            Path: '/websub/subscribe'
            Method: post
            PayloadFormatVersion: '1.0'
      Environment:
        Variables:
          WEBSUB_VERIFICATION_TOKEN: !Ref WebSubVerificationToken
          WEBHOOK_URL: !Ref WebHookURL
          YOUTUBE_VIDEO_DATA_TABLE_NAME: !Select [1, !Split ['/', !GetAtt YouTubeVideoDataTable.Arn]]