name: reviewdog
on: [pull_request]
jobs:
  golangci:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup go golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: run golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: false
          golangci_lint_flags: '--timeout=5m'
