name: test
on: [pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup go golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: run vet
        run: go vet ./...
      - name: run test
        run: go test ./...
